
server:
  port: 9002
  servlet:
    context-path: /${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: note
  jta:
    logDir: target/${spring.application.name}-logs
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_schema: note
    database: mysql
    hibernate:
      dialect: ${spring.jpa.properties.hibernate.dialect}
      ddl-auto: none
    show-sql: false
    format_sql: true
  jackson:
    time-zone: Asia/Rangoon
    joda-date-time-format: dd-MM-yyyy HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    mapper:
      sort-properties-alphabetically: true
  datasource:
    url: jdbc:mysql://localhost:3306/note?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# Logging
logging:
  level:
    root: INFO
    com.aungmyohtwe.note: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.controllers: INFO
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.ORACLE: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger.%M - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
